version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres_container
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./Database/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env

  flask-app:
    build:
      context: ./Backend  # Build from the current directory
    container_name: flask_app_container
    environment:
      FLASK_ENV: development
    ports:
      - "5001:5001"
    depends_on:
      - postgres
    volumes:
      - ./Backend:/app  # Mount the current directory to /app in the container
    env_file:
      - .env  # Load environment variables from .env

  frontend:
    build:
      context: ./Frontend
    platform: linux/arm64
    container_name: react_frontend_container
    ports:
      - "3000:3000"  # Map host port 3000 to Vite's default port 5173
    volumes:
      - ./Frontend:/app  # Mount the frontend directory for live updates
    stdin_open: true
    tty: true

volumes:
  pg_data: