version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres_container
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - my_network
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./Database/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env

  flask-app:
    build:
      context: ./Backend  # Build from the current directory
    container_name: flask_app_container
    environment:
      FLASK_ENV: development
    ports:
      - "5001:5001"
    networks:
      - my_network
    depends_on:
      - postgres
    volumes:
      - ./Backend:/app  # Mount the current directory to /app in the container
    env_file:
      - .env  # Load environment variables from .env

  node-app:
    build:
      context: ./Frontend  # Adjust the path to your Node.js Dockerfile directory
    container_name: node_app_container
    ports:
      - "3000:3000"
    depends_on:
      - flask-app
    volumes:
      - ./Frontend:/app  # Mount the Frontend directory to /app in the container

volumes:
  pg_data:

networks:
  my_network:
    driver: bridge