# Imports
FROM postgres:16.2
FROM postgres:latest

# Copy sql script into container
COPY shared_grocery_service.sql /docker-entrypoint-shared_grocery_servicedb.d/

# Expose PostgreSQL port
EXPOSE 5432


# Set up variables so credentials can then be pulled from the .env file
ARG DB_USER
ARG DB_PASSWORD
ARG DB_NAME

ENV DB_USER=$DB_USER
ENV DB_PASSWORD=$DB_PASSWORD
ENV DB_NAME=$DB_NAME