name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Add SSH Key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
    - name: Deploy to Azure VM
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          # Navigate to project directory, else clone it
          cd Alex-Ethan-Sonali-Hannah-SEPP-Project || (git clone https://github.com/alexgburnet/Alex-Ethan-Sonali-Hannah-SEPP-Project.git && cd Alex-Ethan-Sonali-Hannah-SEPP-Project)

          # Pull latest changes
          git pull origin main

          chmod +x deploy.sh
          
          # Use run script
          ./deploy.sh
        EOF