name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Add SSH Key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
    - name: Deploy to Azure VM
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
          # Exit on error
          set -e
          
          # Navigate to project directory, else clone it
          cd Alex-Ethan-Sonali-Hannah-SEPP-Project || (git clone https://github.com/alexgburnet/Alex-Ethan-Sonali-Hannah-SEPP-Project.git && cd Alex-Ethan-Sonali-Hannah-SEPP-Project)

          # Pull latest changes
          git pull origin main

          # Set environment variables
          echo "DB_USER=${DB_USER}" > .env
          echo "DB_PASSWORD=${DB_PASSWORD}" >> .env
          echo "DB_NAME=${DB_NAME}" >> .env

          # Navigate to Frontend and build the project
          cd Frontend
          npm run build
          cd ..

          # Stop and remove existing containers, then rebuild and restart
          sudo docker-compose down -v
          sudo docker-compose up --build -V
        EOF
      env:
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_NAME: ${{ secrets.DB_NAME }}